version: '2'
services:
  elasticsearch:
    build: ./docker/elasticsearch
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
        - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
        - 9200:9200
    expose:
        - 9300
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    build: ./docker/kibana
    links:
        - elasticsearch:elasticsearch
    ports:
        - 5601:5601

volumes:
    elasticsearch-data:
        driver: local
